server:
  port: 8080
  servlet:
    context-path: /luceneSearch
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lucenedb?useUnicode=true&characterEncoding=utf8&userSSL=false&serverTimezone=Asia/Shanghai
    username: kimoro
    password: 758481
  # thymeleaf
  thymeleaf:
    cache: false #关闭缓存

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package是为了配置xml文件中resultType返回值的包位置
  type-aliases-package: com.yyy.domain
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true